apiVersion: v1
appVersion: "latest"
description: Minimal forward authentication service that provides Google oauth based login and authentication for the traefik reverse proxy 
name: traefik-forward-auth
version: 0.1.0
keywords:
  - traefik-forward-auth
  - traefik
  - oauth
home: https://github.com/thomseddon/traefik-forward-auth
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
