apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traefik-forward-auth.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik-forward-auth.name" . }}
    helm.sh/chart: {{ include "traefik-forward-auth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "traefik-forward-auth.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "traefik-forward-auth.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "traefik-forward-auth.fullname" . }}
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "traefik-forward-auth.fullname" . }}
                  key: clientSecret
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "traefik-forward-auth.fullname" . }}
                  key: secret
            - name: WHITELIST
              value: {{ join "," .Values.traefikForwardAuth.whitelist | quote }}
            - name: COOKIE_SECURE
              value: {{ .Values.traefikForwardAuth.cookieSecure | quote }}
            - name: DOMAIN
              value: {{ required ".Values.traefikForwardAuth.domain is required" .Values.traefikForwardAuth.domain | quote }}
            - name: AUTH_HOST
              value: {{ required ".Values.traefikForwardAuth.authHost is required" .Values.traefikForwardAuth.authHost | quote }}
          ports:
            - name: http
              containerPort: 4181
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
