apiVersion: v1
kind: Secret
metadata:
  name: {{ template "traefik-forward-auth.fullname" . }}
type: Opaque
data:
  clientId: {{ required "traefikForwardAuth.clientId is required" .Values.traefikForwardAuth.clientId | b64enc | quote }}
  clientSecret: {{ required "traefikForwardAuth.clientSecret is required" .Values.traefikForwardAuth.clientSecret | b64enc | quote }}
  {{- if .Values.traefikForwardAuth.secret }}
  secret: {{ .Values.traefikForwardAuth.secret | b64enc }}
  {{ else }}
  secret: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}